### ISSUE TITLE
Add favourite files to "Go to File…" palette

### ISSUE THREAD

**Issue by myfonj** [oleg-shilo/Favorites.vscode#50]
This is just a "nice to have" feature idea:

Would it be possible to pre-populate ("pollute") the `Ctrl+P` list in a new workspace or non-workspace with favourite files from all lists (or just the "default" one)?

It would be super nice convenience shaving off considerable amount of cognitive overhead when muscle-memory seeking for some "globally well-known file" from a new workspace or after profile migration.

---

It is true that (most) opened files get into the `Ctrl+R` ("Open Recent…") palette, but I haven't found a rule when this happens and whether it is reliable across workspaces. And it does not seem to work for files that start in the "preview" mode, or something.  Personally I'd prefer to have favourites in the "Go to File…" all the times, since this presumably the real intended command to "go to" (pun quite indented).

**Comment by oleg-shilo** [comment]
It's a very good and easy-to-implement feature. Good idea. 
I would probably remove the connection to the workspace. Particularly because the workspace already implements this behaviour - every workspace keeps its own list of open files.

We can simply do "Open all files in a new window".
Will it give you what you are looking for?

**Comment by myfonj** [comment]
> We can simply do "Open all files in a new window".
> Will it give you what you are looking for?

Hm, I see bulk-opening all favourites would be viable way to pragmatically populate "Go to" with entire list, relying on the native VSC functionality, so yes, it would bring me what I am after, presumably only in the context of the current workspace. (I see there is already `favorites.open_all_files` command for that(?))

Yet actually it wasn't precisely what I imagined as the ideal solution: I currently have more than 50 favourites (basically all configs and "dotfiles" of my setup and some notes and scrapbooks) and I'd like to avoid opening them all and triggering language servers and extension and whatnot if possible. The ideal use case for me would be that any file linked in the list would just "be" present in the "Go To" list, regardless I had or I had not opened it in the past in given workspace.

I wouldn't be surprised if there was no suitable API for that, so the "bulk-open" workaround would be the only way for us to take. I presume it would have to boil down to:
- check `workbench.editor.enablePreview` and set it to `false`,
- invoke `favorites.open_all_files`,
- invoke `workbench.action.closeAllEditors` (or ideally close only newly opened ones),
- restore `workbench.editor.enablePreview` if was `true` before.

Interestingly, I tried doing this now manually in a "no folder" workspace (which is opened upon VSCs "cold start" for me) and it indeed kept files in the "Go to" list after closing them, but sadly it did not preserve the list to next start (not sure why), so even this would have its culprits it seems.

**Comment by oleg-shilo** [comment]
Sorry, I missed the point... you are specifically about "Go to file " command. Is it right?
![image](https://github.com/user-attachments/assets/466872e3-5188-4f5d-b644-06a05040c1e8)

Well it is doable, as long as VSCode exposes the API for that. Will have a look at it.

> favorites.open_all_files

is different. It does exactly what it says. Opens all files. But if you do not want to open them but only be ready to open then we indeed need GoToFile.

**Comment by myfonj** [comment]
> you are specifically about "Go to file " command. Is it right?

Oh, yes, exactly, the `workbench.action.quickOpen` (*Go to File…*) I should probably have articulated it more clearly, sorry.

It is usually (by default) bound to simple <kbd>Ctrl</kbd>+<kbd>P</kbd> (without the <kbd>Shift</kbd>: doing it with the <kbd>Shift</kbd> opens the very same palette but prefills the `>` command prefix there, thus making it **the** *"command palette"*, by the way).

![Visual Studio Code window with "NO FOLDER OPENED" and opened palette with empty input showing placeholder text that reads "Search files by name (append : to go to line or @ to go to symbol)"](https://github.com/user-attachments/assets/c6a71e7b-2297-405b-a9f3-edf04cb6ae80)

**Comment by myfonj** [comment]
> [`favorites.open_all_files`] does exactly what it says. Opens all files.

NB yes, just only with the disabled `workbench.editor.enablePreview`, as [Hints/Tips of your Readme](https://github.com/oleg-shilo/Favorites.vscode?tab=readme-ov-file#hintstips) suggest. (If ext can read prefs and give user the link such as `vscode://settings/workbench.editor.enablePreview`, maybe there could be a conditional prompt "To really open all files, please turn this pref off first.")

**Comment by oleg-shilo** [comment]
Done. Thank you for good suggestions.

Changes:  
  - Added `Favorites: Quick pick` command
    `Ctrs+Shift+P`:
    ![image](https://github.com/user-attachments/assets/1ebdd829-912a-42a3-8bff-6a0accefcd4c)
    Then:
    ![image](https://github.com/user-attachments/assets/ff63a860-f4ad-4172-9edb-e6a594cf3c47)
  - Added user prompt if detected that VSCode have preview mode enabled which impacts the UX of opening the files from the favorites list. The prompt has option to fix the incompatible setting.
    ![image](https://github.com/user-attachments/assets/07b772cf-23bb-443a-808e-bd5949ddd24e)

**Comment by myfonj** [comment]
Sorry for late response, changes are great, and really appreciate your swiftness here :]
Using new `Favorites: Quick pick` (mapped it to <kbd>Ctrl</kbd><b><kbd>Alt</kbd></b><kbd>P</kbd>), and it works quite well, only with one strange drawback: it seems that all Favourites with custom labels (pipe something) or `$USERPROFILE` substitution are ignored from the pick list.

```Plaintext
# something with subst:
$USERPROFILE\AppData\Roaming\Mozilla\Firefox\installs.ini
# something with label:
C:\Windows\System32\drivers\etc\hosts|hostfile
```

Is it intentional?

**Comment by myfonj** [comment]
(Ups, mis-click, didn't want to close it right now, sorry.)

**Comment by oleg-shilo** [comment]
Thank you for getting back on this.
Will have a look.

**Comment by oleg-shilo** [comment]
> Is it intentional?

Well, partially 😄

Expanding envars - 'no'. I just missed it. Fixed in the very last release v1.6.7.

Removing some entries - 'yes'. The intention was, to put in the quick list the only entries that are files (not folders). Thus the path must exist and it has to be local (so I can check if it is a file or a dir). 

Though I reconsidered this approach and the latest (published) release shows all entries and used icons to indicate the nature of the item:
 
![Image](https://github.com/user-attachments/assets/3388ff62-fd2f-419f-aebb-7598faff2d45)

**Comment by myfonj** [comment]
That looks really nice! 

Sadly, at this point I am getting `TypeError: map.get(...) is not a function at c:\apps\VSCode\data\extensions\oleg-shilo.favorites-1.6.7\out\src\extension.js:475:52` in the Extension Host output, what seems to correspond to
https://github.com/oleg-shilo/Favorites.vscode/blob/30196ba8528903ae573aca9dc72cbb285fefd0d3/src/extension.ts#L579
so the picker lists nothing at all for me.

But looking at the graphic it seems perfect.

---

I must admit that having a separate picker is probably even better than polluting the native one I suggested initially. And I think that releasing the "file exists" check is way to go; when user puts a path to some non-existent file there, they most probably have some reason for that.

**Comment by oleg-shilo** [comment]
> releasing the "file exists" check is way to go; when user puts a path to some non-existent file there, they most probably have some reason for that.

Exactly. And if it was a wrong entry then the IDE is reporting it nicely. 
I had "file exists" check as a way to hide the dirs as opposed to the file items. Having a mix of both could be confusing. But since I found the icons as a visual aid to avoid confusion I no longer need to filter items so "file exist" could be removed.

As for `map.get`, it's really strange. The function does exists:

![Image](https://github.com/user-attachments/assets/0e5adade-ceb3-44fe-a551-7120b9b8dc02)

And the screenshot I shared was taken from the working system. And I have just updated the extension on another system and it's all OK.

Thus I see only two reasons for the failure:
1. Your VSCode environment somehow misses the `map.get` implementation.
    Updating VSCode may help if it is the case.
2. Somehow the content of your list is upsetting `map.get` API.
   You can easily check it by having an empty list with only a single line of a valid document file.

I also noticed a strange thing in your scenario that IU cannot explain.  
`map.get` is only executed after the user selects the item from the QuickPick list. But you are saying that the list is empty...

![Image](https://github.com/user-attachments/assets/d43d4716-953d-4283-87f0-b61bebf9e589)

**Comment by myfonj** [comment]
Tried the ext with a clean profile on VSC Insiders and found out that **empty line** breaks the parsing right now. (I have usually `files.insertFinalNewline` enabled, so it's quite hard for me not to have at least one in any file after save without changing the prefs.)

Without empty lines it indeed works as described, so good work!

For current version I have three remarks:

1. `# …comments` are listed,
2. `\n\n` (as told) empty lines break parsing (or something),
3. `…|Labels` prevent searching by the "real" filename/path.

```Plaintext
# 1. Comment (presumably should not be listed (?))

# ↑ 2. line break, should be skipped
$USERPROFILE\.gitconfig|asdf
# ↑ 3. ideally, that file should be found both for "asdf" *and* "git"
```

(Not sure if it would make sense to make the resolved `$USERPROFILE` also part of the searchable content, but lean towards it would not.)

These are really nice-to-have non-vital features I can live without, so no pressure, please!

**Comment by oleg-shilo** [comment]
That's OK, I will simply filter out the empty likes. 
It's an easy fix

**Comment by oleg-shilo** [comment]
>sense to make the resolved  

:) I was actually tossing if I should do it or not...
Will change it too

**Comment by oleg-shilo** [comment]
Done. Published v1.6.8

>$USERPROFILE\.gitconfig|asdf
>\# ↑ 3. ideally, that file should be found both for "asdf" *and* "git"

QuickPick only finds what is displayed in the dropdown. Thus if it is a path the "git" will pick it. If it is the alias the "asdf" will.

I opted to show the alias. The rationale: user decided to hide the thank and see in the favorites tree the alias instead. So QuickPick should do the same.

**Comment by myfonj** [comment]
I have updated to `1.6.8` where quick picker listing works again, but actual **opening any item from there throws** familiar `TypeError: map.get(...) is not a function at ___\extensions\oleg-shilo.favorites-1.6.8\out\src\extension.js:474:44` https://github.com/oleg-shilo/Favorites.vscode/blob/a30dafdfbd6e29bb0b92ca4a3446c6bbe1ef0ab4/src/extension.ts#L578 (tried both in a clean Insiders and my messy stable VSC, with just a single existing path).

Does it really work in your setup?

Also, I've noticed that entries with no path (`| kinda label`) (ab)used for visual separation of blocks in the sidebar view, as well as `# comments` are also preset in the quick-pick list (as `⚠ invalid paths`); I guess such path-less entries should be omitted from the pick list, just like empty lines (?)

And also, for some reason no mater how I tried to label the `Default.list.txt` now, its path is always listed instead.

Sample:

```
|/▔  Automation  ▔\
$USERPROFILE\Documents\AutoHotkeyU64.ahk
# ...etc
#|
|/▔  Conf & logs  ▔\
c:\apps\VSCode\data\user-data\User\globalStorage\favorites.user\Default.list.txt|👉☛☞🖛🖙🖝This list🖜🖘🖚☜☚👈
c:\apps\Node\global_node_modules\etc\npmrc|NPM - system (Node..\etc\npmrc)
$USERPROFILE\.npmrc|NPM user (~\.npmrc)
c:\Windows\System32\drivers\etc\hosts|hosts
# ...etc
#|
|/▔  Visual Studio Code  ▔\
c:\apps\VSCode\data\argv.json
c:\apps\VSCode\data\user-data\User\keybindings.json
c:\apps\VSCode\data\user-data\User\settings.json
c:\apps\VSCode\data\user-data\User\tasks.json
c:\apps\VSCode\data\user-data\User\snippets\global.code-snippets
# ...etc
```

![List contains entries such as `/▔  Automation  ▔\` and even `# ...etc`](https://github.com/user-attachments/assets/51de8806-c190-485c-afc1-6fb5dd4f0302)

**Comment by oleg-shilo** [comment]
OMG, It's really embarrassing. 

As a last testing point before the release, I tried to test the extension with a broken path and forgot to delete the test code before the build. This is the code that you quoted in your post. It cannot possibly open any file.

![Image](https://github.com/user-attachments/assets/6c1b0eaa-88df-421b-b2f8-689b5d818d72)

I do apologise for that.

It's fixed now. Please update the extension. 
Please let me know if it worked in your environment (or at all)
I did test it in mine now :)

**Comment by myfonj** [comment]
No problem :) inadvertently pushing experimentally broken code to prod, been there, done that :]
Plus, until the feature is announced and documented in the readme, it technically does not exist, so there is absolutely no problem in breaking it.

v1.6.9 works perfectly indeed, real pleasure to have reliable Favorites: Quick Pick palette in any project now 🎉

And about that empty (path-less) labels present there: they somehow grew on me. Is feels a bit clunky, but on the other hand, the fact that upon invoking the palette I basically see the exact same content as in the list.txt file makes the palette even more intuitive and familiar, what I hadn't realized initially.

**Comment by myfonj** [comment]
Ha, seems we can close this feature request, long overdue; I see it is even documented in the readme.
Really using this daily, so thanks again! :]

**Comment by oleg-shilo** [comment]
I typically let the creator of the issue close it after he/she is satisfied that it is indeed resolved. 
If the creator forgets about it, then I close it by myself if it was resolved more than a month ago.
In this case, I just missed it. 
Thank you for pointing that out.
